init:
  - ps: if ( ($env:APPVEYOR_REPO_BRANCH -eq 'master') -and ($env:APPVEYOR_REPO_TAG -eq $TRUE) ) { $env:APPVEYOR_BUILD_VERSION = $env:APPVEYOR_REPO_TAG_NAME }

image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: $(appveyor_build_version)
  auth_token: $(GITHUB_TOKEN)
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key: $(NUGET_API_KEY)
  on:
    APPVEYOR_REPO_TAG: true
